services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/app
    tty: true
    image: lambda-selenium-sample
    container_name: lambda-selenium-sample
    environment:
      TZ: "Asia/Tokyo"
    network_mode: "host"
